Feature branch : Project: Authentication
KossySteve/members_only pull request #2
Opened 2020-09-18 01:13 UTC by KossySteve

A microverse project to work with authentcation in rails, creating posts and restricting non_users from access to view posts.
Please ReadMe file on how to run project

2020-09-18 02:16 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello team 👋 . Progress is a decent one. 
The project, however, is still undone, kindly take a gape at the propositions and work on the requirements below. 👇 

### Christian Otieno (TSE)

2020-09-18 02:16 UTC, christianotieno commented on README.md
> +
##  Improvement  on the commit messages
- [ ] In your next iteration, I would urge to commit as often as posbblie to make it easy to follow the development journey let's aim to make our commits more descriptive ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-09-18 02:16 UTC, christianotieno commented on app/controllers/registrations_controller.rb
> +    end
## Implent user sign out feature
- [ ] Now that our user can sign up, we don't have a way of them logging out. Create a method to enable this feature. Make sure  I as User I can successfully sign_out ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_out_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

2020-09-18 02:16 UTC, christianotieno commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
## Commented out code
- [ ] Comments: It’s better to delete these **commented pieces of code**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-09-18 02:16 UTC, christianotieno commented on app/views/devise/sessions/new.html.erb
> +
## Provide  sign in/signup and sign out links to the user
- [ ] Once we have implemented the logic for a user to log out, let's make ensure we have a Sign in/Sign out links present in any our views here ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_out_link_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))

2020-09-18 02:16 UTC, christianotieno commented on app/views/posts/index.html.erb
> +        <td><%# link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
## Commented out code
- [ ] Comments: It’s better to delete these **commented pieces of code**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-09-21 17:16 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****
**[OPTIONAL]**

- [ ] There should be **absolutely no logic in your views**. All view related logic should be encapsulated in view helpers `app/helpers/*_helper.rb`.  
    - As this was not pointed out to you in your previous review I have marked it as optional but I highly recommend making these changes as it is a requirement and it is good practice. 
   - I have added comments below of the logic in your views that should be in helpers.

_P.S.  all requested changes marked by [OPTIONAL] are not required. It is up to you whether or not you would like to do them_ 😄 

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-09-21 17:16 UTC, BrittanyBlake commented on app/views/posts/_form.html.erb
> +  <% end %>
- View-related logic should be encapsulated in View helpers `(app/helpers/*_helper.rb)`

2020-09-21 17:16 UTC, BrittanyBlake commented on app/views/posts/index.html.erb
> +        <%end%>
- View-related logic should be encapsulated in View helpers `(app/helpers/*_helper.rb)`

2020-09-21 19:17 UTC, merged